version: "3.9"
services:
  db:
    image: postgres:15-bullseye
    container_name: backend-ae
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"